load ../../../src/probabilistic-model/dns
load ../../../src/probabilistic-model/sampler
load ../../../src/probabilistic-model/properties
load ../attacker

--- This is variant (c) of the NXNS attack, i.e., the victim are the root servers.

mod TEST is
  inc SAMPLER + APMAUDE + DNS + PROPERTIES + ATTACKER .

  --- uncomment to enable MaxFetch(1) mitigation
  --- eq maxFetch? = true .
  eq maxFetchParam = 1 .

  op testTTL : -> Float .
  eq testTTL = 3600.0 . --- Note that this is in time units, not seconds

  op q : -> Query .
  eq q = query(1, 'nxdomain . 'attacker1 . 'com . root, a) .

  ops mAddr cAddr rAddr : -> Address .

  --- "SBELT": fallback if there are no known name servers
  op sb : -> ZoneState .
  eq sb = < root ('a . 'root-servers . 'net . root |-> addrRoot) > .

  op cache : -> Cache .
  eq cache =
    cacheEntry(< 'attacker1 . 'com . root, ns, testTTL, 'ns . 'attacker1 . 'com . root >, 1)
    cacheEntry(< 'ns . 'attacker1 . 'com . root, a, testTTL, addrNSattacker1 >, 1)
    cacheEntry(< 'attacker2 . 'com . root, ns, testTTL, 'ns . 'attacker2 . 'com . root >, 1)
    cacheEntry(< 'ns . 'attacker2 . 'com . root, a, testTTL, addrNSattacker2 >, 1) .

  ops addrRoot addrNScom addrNSattacker1 addrNSattacker2 : -> Address .

  ops zoneRoot zoneCom zoneAttacker : -> List{Record} .
  eq zoneRoot =
    --- authoritative data
    < root, soa, testTTL, soaData(testTTL) > --- dummy value
    < root, ns, testTTL, 'a . 'root-servers . 'net . root >

    --- non-authoritative data
    < 'a . 'root-servers . 'net . root, a, testTTL, addrRoot >
    < 'com . root, ns, testTTL, 'ns . 'com . root >
    < 'ns . 'com . root, a, testTTL, addrNScom > . --- glue

  eq zoneCom =
    --- authoritative data
    < 'com . root, soa, testTTL, soaData(testTTL) >
    < 'com . root, ns, testTTL, 'ns . 'com . 'root >
    < 'ns . 'com . root, a, testTTL, addrNScom >

    --- non-authoritative data
    < 'attacker1 . 'com . root, ns, testTTL, 'ns . 'attacker1 . 'com . root >
    < 'ns . 'attacker1 . 'com . root, a, testTTL, addrNSattacker1 > --- glue

    < 'attacker2 . 'com . root, ns, testTTL, 'ns . 'attacker2 . 'com . root >
    < 'ns . 'attacker2 . 'com . root, a, testTTL, addrNSattacker2 > . --- glue

  op initConfig : -> Config .
  eq initConfig = run(initState, limit) .

  eq initState = { 0.0 | nil }
    --- Preliminaries
    initMonitor(mAddr)
    [id, to cAddr : start, 0]

    < cAddr : Client | queries: q, resolver: rAddr, notifyDone: nullAddr >
    < rAddr : Resolver | cache: cache,  --- assuming the attacker.com name servers are cached
                         nxdomainCache: nilNxdomainCache,
                         nodataCache: nilNodataCache,
                         sbelt: sb,
                         workBudget: emptyIN,
                         blockedQueries: eptQSS,
                         sentQueries: eptQSS >

    --- Root name server
    < addrRoot : Nameserver | db: zoneRoot, queue: nilQueue >
    --- .com authoritative name server
    < addrNScom : Nameserver | db: zoneCom, queue: nilQueue >

    --- Malicious name servers
    --- Note that we split this into two different name servers for convenience; the functionality could also be on the
    --- same name server.
    maliciousNXNSNameserver(addrNSattacker1, 'attacker2 . 'com . root, 5, 1, testTTL)
    maliciousNXNSNameserver(addrNSattacker2, root, 10, 1, testTTL) .

endm

--- uncomment for debugging purposes
--- set trace on .

set trace condition off . --- This does not seem to work
set trace whole off .
set trace substitution off .
set trace mb off .
set trace eq off .
set trace rl on . --- on
set trace select off .
set trace rewrite off .
set trace body off .
set trace builtin off .

rew initConfig .
--- rew numActorMsgsRecvd(addrRoot, initConfig) .
--- rew numActorMsgsSent(cAddr ; addrNSattacker1 ; addrNSattacker2, initConfig) .
rew msgAmpFactor(cAddr ; addrNSattacker1 ; addrNSattacker2, addrRoot, initConfig) .
