load ../../attacker-models/common/attacker

--- some constants
mod TEST is
  inc ATTACKER-COMMON .

  op testTTL : -> Float .
  eq testTTL = 3600.0 .

  op cAddr : -> Address .

endm

--- fakeName unit tests
red fakeName(0, 1, 'attacker . 'com . root) == label2(0, 0) . 'attacker . 'com . root .
red fakeName(0, 5, 'attacker . 'com . root)
  == label2(0, 4) . label2(0, 3) . label2(0, 2) . label2(0, 1) . label2(0, 0) . 'attacker . 'com . root .
red fakeName(1, 5, 'attacker . 'com . root)
  == label2(1, 4) . label2(1, 3) . label2(1, 2) . label2(1, 1) . label2(1, 0) . 'attacker . 'com . root .
red fakeName(0, 0, 'attacker . 'com . root) == 'attacker . 'com . root .

--- fakeDelegationRecords unit tests
red fakeDelegationRecords(1, 0, 1, 'sub . 'attacker . 'com . root, 'victim . 'com . root, testTTL)
  == < 'sub . 'attacker . 'com . root, ns, testTTL, label2(0, 0) . 'victim . 'com . root > .
red fakeDelegationRecords(2, 0, 1, 'sub . 'attacker . 'com . root, 'victim . 'com . root, testTTL)
  == < 'sub . 'attacker . 'com . root, ns, testTTL, label2(0, 0) . 'victim . 'com . root >
     < 'sub . 'attacker . 'com . root, ns, testTTL, label2(1, 0) . 'victim . 'com . root > .
red fakeDelegationRecords(1, 0, 2, 'sub . 'attacker . 'com . root, 'victim . 'com . root, testTTL)
  == < 'sub . 'attacker . 'com . root, ns, testTTL, label2(0, 1) . label2(0, 0) . 'victim . 'com . root > .
red fakeDelegationRecords(2, 0, 2, 'sub . 'attacker . 'com . root, 'victim . 'com . root, testTTL)
  == < 'sub . 'attacker . 'com . root, ns, testTTL, label2(0, 1) . label2(0, 0) . 'victim . 'com . root >
     < 'sub . 'attacker . 'com . root, ns, testTTL, label2(1, 1) . label2(1, 0) . 'victim . 'com . root > .

--- genQueries unit tests
red genQueries(1, 'victim . 'com . root, 1, a, cAddr)
  == query(clientId(cAddr, 1), label2(1, 0) . 'victim . 'com . root, a) .
red genQueries(2, 'victim . 'com . root, 1, a, cAddr)
  == query(clientId(cAddr, 2), label2(2, 0) . 'victim . 'com . root, a)
     query(clientId(cAddr, 1), label2(1, 0) . 'victim . 'com . root, a) .
red genQueries(2, 'victim . 'com . root, 2, a, cAddr)
  == query(clientId(cAddr, 2), label2(2, 1) . label2(2, 0) . 'victim . 'com . root, a)
     query(clientId(cAddr, 1), label2(1, 1) . label2(1, 0). 'victim . 'com . root, a) .

--- splitList1 unit tests
red splitList1(
    < label2(0, 2) . 'target . 'com . root, cname, testTTL, label2(0, 1) . 'intermediary . 'com . root >
    < label2(0, 1) . 'intermediary . 'com . root, cname, testTTL, label2(0, 0) . 'target . 'com . root >
    < label2(0, 0) . 'target . 'com . root, txt, testTTL, nullAddr >
) == < label2(0, 2) . 'target . 'com . root, cname, testTTL, label2(0, 1) . 'intermediary . 'com . root >
     < label2(0, 0) . 'target . 'com . root, txt, testTTL, nullAddr > .

red splitList1(
    < label2(0, 3) . 'target . 'com . root, cname, testTTL, label2(0, 2) . 'intermediary . 'com . root >
    < label2(0, 2) . 'intermediary . 'com . root, cname, testTTL, label2(0, 1) . 'target . 'com . root >
    < label2(0, 1) . 'target . 'com . root, cname, testTTL, label2(0, 0) . 'intermediary . 'com . root >
    < label2(0, 0) . 'intermediary . 'com . root, txt, testTTL, nullAddr >
) == < label2(0, 3) . 'target . 'com . root, cname, testTTL, label2(0, 2) . 'intermediary . 'com . root >
     < label2(0, 1) . 'target . 'com . root, cname, testTTL, label2(0, 0) . 'intermediary . 'com . root > .

--- splitList2 unit tests
red splitList2(
    < label2(0, 2) . 'target . 'com . root, cname, testTTL, label2(0, 1) . 'intermediary . 'com . root >
    < label2(0, 1) . 'intermediary . 'com . root, cname, testTTL, label2(0, 0) . 'target . 'com . root >
    < label2(0, 0) . 'target . 'com . root, txt, testTTL, nullAddr >
) == < label2(0, 1) . 'intermediary . 'com . root, cname, testTTL, label2(0, 0) . 'target . 'com . root > .

red splitList2(
    < label2(0, 3) . 'target . 'com . root, cname, testTTL, label2(0, 2) . 'intermediary . 'com . root >
    < label2(0, 2) . 'intermediary . 'com . root, cname, testTTL, label2(0, 1) . 'target . 'com . root >
    < label2(0, 1) . 'target . 'com . root, cname, testTTL, label2(0, 0) . 'intermediary . 'com . root >
    < label2(0, 0) . 'intermediary . 'com . root, txt, testTTL, nullAddr >
) == < label2(0, 2) . 'intermediary . 'com . root, cname, testTTL, label2(0, 1) . 'target . 'com . root >
     < label2(0, 0) . 'intermediary . 'com . root, txt, testTTL, nullAddr > .

--- unchainedRecords unit tests
red unchainedRecords('target . 'com . root, 'intermediary . 'com . root, 2, 0, testTTL)
  == < label2(0, 2) . 'target . 'com . root, cname, testTTL, label2(0, 1) . 'intermediary . 'com . root >
     < label2(0, 1) . 'intermediary . 'com . root, cname, testTTL, label2(0, 0) . 'target . 'com . root >
     < label2(0, 0) . 'target . 'com . root, txt, testTTL, nullAddr > .

red unchainedRecords('target . 'com . root, 'intermediary . 'com . root, 3, 0, testTTL)
  == < label2(0, 3) . 'target . 'com . root, cname, testTTL, label2(0, 2) . 'intermediary . 'com . root >
     < label2(0, 2) . 'intermediary . 'com . root, cname, testTTL, label2(0, 1) . 'target . 'com . root >
     < label2(0, 1) . 'target . 'com . root, cname, testTTL, label2(0, 0) . 'intermediary . 'com . root >
     < label2(0, 0) . 'intermediary . 'com . root, txt, testTTL, nullAddr > .

--- unchainedRecordsTarget unit tests
red unchainedRecordsTarget('target . 'com . root, 'intermediary . 'com . root, 2, 0, testTTL)
  == < label2(0, 2) . 'target . 'com . root, cname, testTTL, label2(0, 1) . 'intermediary . 'com . root >
     < label2(0, 0) . 'target . 'com . root, txt, testTTL, nullAddr > .

red unchainedRecordsTarget('target . 'com . root, 'intermediary . 'com . root, 3, 0, testTTL)
  == < label2(0, 3) . 'target . 'com . root, cname, testTTL, label2(0, 2) . 'intermediary . 'com . root >
     < label2(0, 1) . 'target . 'com . root, cname, testTTL, label2(0, 0) . 'intermediary . 'com . root > .

--- unchainedRecordsIntermediary unit tests
red unchainedRecordsIntermediary('target . 'com . root, 'intermediary . 'com . root, 2, 0, testTTL)
  == < label2(0, 1) . 'intermediary . 'com . root, cname, testTTL, label2(0, 0) . 'target . 'com . root > .

red unchainedRecordsIntermediary('target . 'com . root, 'intermediary . 'com . root, 3, 0, testTTL)
  == < label2(0, 2) . 'intermediary . 'com . root, cname, testTTL, label2(0, 1) . 'target . 'com . root >
     < label2(0, 0) . 'intermediary . 'com . root, txt, testTTL, nullAddr > .

--- unchainedQuery unit tests
red unchainedQuery('target . 'com . root, 3, 0) == query(0, label2(0, 3) . 'target . 'com . root, txt) .

--- unchainedQminRecords unit tests
red unchainedQminRecords('target . 'com . root, 'intermediary . 'com . root, 2, 0, 2, testTTL)
  == < label2(0, 1) . label2(0, 0) . label2(0, 2) . 'target . 'com . root, cname, testTTL,
          label2(0, 1) . 'intermediary . 'com . root >
     < label2(0, 1) . 'intermediary . 'com . root, cname, testTTL,
          label2(0, 1) . label2(0, 0) . label2(0, 0) . 'target . 'com . root >
     < label2(0, 1) . label2(0, 0) . label2(0, 0) . 'target . 'com . root, txt, testTTL, nullAddr > .

red unchainedQminRecords('target . 'com . root, 'intermediary . 'com . root, 3, 0, 2, testTTL)
  == < label2(0, 1) . label2(0, 0) . label2(0, 3) . 'target . 'com . root, cname, testTTL,
          label2(0, 2) . 'intermediary . 'com . root >
     < label2(0, 2) . 'intermediary . 'com . root, cname, testTTL,
          label2(0, 1) . label2(0, 0) . label2(0, 1) . 'target . 'com . root >
     < label2(0, 1) . label2(0, 0) . label2(0, 1) . 'target . 'com . root, cname, testTTL,
          label2(0, 0) . 'intermediary . 'com . root >
     < label2(0, 0) . 'intermediary . 'com . root, txt, testTTL, nullAddr > .

--- unchainedQminRecordsTarget unit tests
red unchainedQminRecordsTarget('target . 'com . root, 'intermediary . 'com . root, 2, 0, 2, testTTL)
  == < label2(0, 1) . label2(0, 0) . label2(0, 2) . 'target . 'com . root, cname, testTTL,
          label2(0, 1) . 'intermediary . 'com . root >
     < label2(0, 1) . label2(0, 0) . label2(0, 0) . 'target . 'com . root, txt, testTTL, nullAddr > .

red unchainedQminRecordsTarget('target . 'com . root, 'intermediary . 'com . root, 3, 0, 2, testTTL)
  == < label2(0, 1) . label2(0, 0) . label2(0, 3) . 'target . 'com . root, cname, testTTL,
          label2(0, 2) . 'intermediary . 'com . root >
     < label2(0, 1) . label2(0, 0) . label2(0, 1) . 'target . 'com . root, cname, testTTL,
          label2(0, 0) . 'intermediary . 'com . root > .

--- unchainedQminRecordsIntermediary unit tests
red unchainedQminRecordsIntermediary('target . 'com . root, 'intermediary . 'com . root, 2, 0, 2, testTTL)
  == < label2(0, 1) . 'intermediary . 'com . root, cname, testTTL,
          label2(0, 1) . label2(0, 0) . label2(0, 0) . 'target . 'com . root > .

red unchainedQminRecordsIntermediary('target . 'com . root, 'intermediary . 'com . root, 3, 0, 2, testTTL)
  == < label2(0, 2) . 'intermediary . 'com . root, cname, testTTL,
          label2(0, 1) . label2(0, 0) . label2(0, 1) . 'target . 'com . root >
     < label2(0, 0) . 'intermediary . 'com . root, txt, testTTL, nullAddr > .

--- unchainedQminQuery unit tests
red unchainedQminQuery('target . 'com . root, 3, 0, 2)
  == query(0, label2(0, 1) . label2(0, 0) . label2(0, 3) . 'target . 'com . root, txt) .

--- idnsQuery unit tests
red idnsQuery('attacker . 'com . root, 1, 0)
  == query(0, label2(0, 0) . label2(0, 0) . 'attacker . 'com . root, a) .
red idnsQuery('attacker . 'com . root, 2, 0)
  == query(0, label2(0, 1) . label2(0, 0) . label2(0, 0) . 'attacker . 'com . root, a) .
