load ../../../../../src/probabilistic-model/dns
load ../../../../../src/probabilistic-model/sampler
load ../../../../../src/probabilistic-model/properties
        
--- Created automatically with Python.
--- This file simulates the Subqueries-Unchained using DNAME chains. It consists
--- of an attacker client query to a resolver which will trigger multiple NS
--- delegations at a victim nameserver. The attacker managed to install some records in
--- this victim nameserver, which trigger a long DNAME chain between the nameserver and
--- the resolver.
--- Attacker: client ; Victim : nameserver
        
mod TEST is
  inc SAMPLER + APMAUDE + DNS + PROPERTIES .

  eq rsvTimeout? = false .
  eq rsvTimeout = 1000.0 .

 
	---  maximum subqueries
	eq maxFetch? = true .
	eq maxFetchParam = 5 .

	eq configWorkBudget = 100 .

	--- enable overall timeout 
	eq rsvOverallTimeout? = true . 
	eq rsvOverallTimeout = 6000.0 . 


         
--- Deactivate QMIN
eq maxMinimiseCount = 0 .


  op testTTL : -> Float .
  eq testTTL = 3600.0 .

  op q : -> Query .
  eq q = query(1, 'del . 'intermediary . 'com . root, a) .


  ops mAddr cAddr rAddr : -> Address .

  --- "SBELT": fallback if there are no known name servers
  op sb : -> ZoneState .
  eq sb = < root ('a . 'root-servers . 'net . root |-> addrRoot) > .

  ops addrRoot addrNScom addrNStargetANS addrNSintermediary : -> Address .

  op cache : -> Cache .
  eq cache =
    cacheEntry(< 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >, 1)
    cacheEntry(< 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS >, 1)
    cacheEntry(< 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >, 1)
    cacheEntry(< 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary >, 1) .


  ops zoneRoot zoneCom zoneTargetANS zoneIntermediary : -> List{Record} .

  eq zoneRoot =
    --- authoritative data
    < root, soa, testTTL, soaData(testTTL) > --- dummy value
    < root, ns, testTTL, 'a . 'root-servers . 'net . root >

    --- non-authoritative data
    < 'a . 'root-servers . 'net . root, a, testTTL, addrRoot >
    < 'com . root, ns, testTTL, 'ns . 'com . root >
    < 'ns . 'com . root, a, testTTL, addrNScom > . --- glue

  eq zoneCom =
    --- authoritative data
    < 'com . root, soa, testTTL, soaData(testTTL) >
    < 'com . root, ns, testTTL, 'ns . 'com . 'root >
    < 'ns . 'com . root, a, testTTL, addrNScom >

    --- non-authoritative data
    < 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >
    < 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS >  --- glue
    < 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >
    < 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary > . --- glue

  eq zoneTargetANS =
    --- authoritative data
    < 'target-ans . 'com . root, soa, testTTL, soaData(testTTL) >
    < 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >
    < 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS >

    

		< 'a1 . 'target-ans . 'com . root , dname, testTTL, 'b1 . 'intermediary . 'com . root >
		< 'c1 . 'target-ans . 'com . root , dname, testTTL, 'd1 . 'intermediary . 'com . root >
		< 'e1 . 'target-ans . 'com . root , dname, testTTL, 'f1 . 'intermediary . 'com . root >
		< 'g1 . 'target-ans . 'com . root , dname, testTTL, 'h1 . 'intermediary . 'com . root >
		< 'i1 . 'target-ans . 'com . root , dname, testTTL, 'j1 . 'intermediary . 'com . root >
		< 'k1 . 'target-ans . 'com . root , dname, testTTL, 'l1 . 'intermediary . 'com . root >


		< 'a2 . 'target-ans . 'com . root , dname, testTTL, 'b2 . 'intermediary . 'com . root >
		< 'c2 . 'target-ans . 'com . root , dname, testTTL, 'd2 . 'intermediary . 'com . root >
		< 'e2 . 'target-ans . 'com . root , dname, testTTL, 'f2 . 'intermediary . 'com . root >
		< 'g2 . 'target-ans . 'com . root , dname, testTTL, 'h2 . 'intermediary . 'com . root >
		< 'i2 . 'target-ans . 'com . root , dname, testTTL, 'j2 . 'intermediary . 'com . root >
		< 'k2 . 'target-ans . 'com . root , dname, testTTL, 'l2 . 'intermediary . 'com . root >


		< 'a3 . 'target-ans . 'com . root , dname, testTTL, 'b3 . 'intermediary . 'com . root >
		< 'c3 . 'target-ans . 'com . root , dname, testTTL, 'd3 . 'intermediary . 'com . root >
		< 'e3 . 'target-ans . 'com . root , dname, testTTL, 'f3 . 'intermediary . 'com . root >
		< 'g3 . 'target-ans . 'com . root , dname, testTTL, 'h3 . 'intermediary . 'com . root >
		< 'i3 . 'target-ans . 'com . root , dname, testTTL, 'j3 . 'intermediary . 'com . root >
		< 'k3 . 'target-ans . 'com . root , dname, testTTL, 'l3 . 'intermediary . 'com . root >

    .

  eq zoneIntermediary =
    --- authoritative data
    < 'intermediary . 'com . root, soa, testTTL, soaData(testTTL) >
    < 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >
    < 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary >

    	--- Malicious delegation
		< 'del . 'intermediary . 'com . root, ns, testTTL, 'sub .  'a1 . 'target-ans . 'com . root >
		< 'del . 'intermediary . 'com . root, ns, testTTL, 'sub .  'a2 . 'target-ans . 'com . root >
		< 'del . 'intermediary . 'com . root, ns, testTTL, 'sub .  'a3 . 'target-ans . 'com . root >


		< 'b1 . 'intermediary . 'com . root , dname, testTTL, 'c1 . 'target-ans . 'com . root >
		< 'd1 . 'intermediary . 'com . root , dname, testTTL, 'e1 . 'target-ans . 'com . root >
		< 'f1 . 'intermediary . 'com . root , dname, testTTL, 'g1 . 'target-ans . 'com . root >
		< 'h1 . 'intermediary . 'com . root , dname, testTTL, 'i1 . 'target-ans . 'com . root >
		< 'j1 . 'intermediary . 'com . root , dname, testTTL, 'k1 . 'target-ans . 'com . root >


		< 'b2 . 'intermediary . 'com . root , dname, testTTL, 'c2 . 'target-ans . 'com . root >
		< 'd2 . 'intermediary . 'com . root , dname, testTTL, 'e2 . 'target-ans . 'com . root >
		< 'f2 . 'intermediary . 'com . root , dname, testTTL, 'g2 . 'target-ans . 'com . root >
		< 'h2 . 'intermediary . 'com . root , dname, testTTL, 'i2 . 'target-ans . 'com . root >
		< 'j2 . 'intermediary . 'com . root , dname, testTTL, 'k2 . 'target-ans . 'com . root >


		< 'b3 . 'intermediary . 'com . root , dname, testTTL, 'c3 . 'target-ans . 'com . root >
		< 'd3 . 'intermediary . 'com . root , dname, testTTL, 'e3 . 'target-ans . 'com . root >
		< 'f3 . 'intermediary . 'com . root , dname, testTTL, 'g3 . 'target-ans . 'com . root >
		< 'h3 . 'intermediary . 'com . root , dname, testTTL, 'i3 . 'target-ans . 'com . root >
		< 'j3 . 'intermediary . 'com . root , dname, testTTL, 'k3 . 'target-ans . 'com . root >

    .


  op initConfig : -> Config .
  eq initConfig = run(initState, limit) .

  eq initState = { 0.0 | nil }
    --- Preliminaries
    initMonitor(mAddr)
    [id, to cAddr : start, 0]

    < cAddr : Client | queries: q, resolver: rAddr, notifyDone: nullAddr >
    < rAddr : Resolver | cache: cache,
                         nxdomainCache: nilNxdomainCache,
                         nodataCache: nilNodataCache,
                         sbelt: sb,
                         workBudget: emptyIN,
                         blockedQueries: eptQSS,
                         sentQueries: eptQSS >

    --- Root name server
    < addrRoot : Nameserver | db: zoneRoot, queue: nilQueue >
    --- .com authoritative name server
    < addrNScom : Nameserver | db: zoneCom, queue: nilQueue >
    --- attacker authoritative name server
    < addrNStargetANS : Nameserver | db: zoneTargetANS, queue: nilQueue >
    --- intermediary.com authoritative name server
    < addrNSintermediary : Nameserver | db: zoneIntermediary, queue: nilQueue > .

endm

--- uncomment for debugging purposes
--- set trace on .

set trace condition off . --- This does not seem to work
set trace whole off .
set trace substitution off .
set trace mb off .
set trace eq off .
set trace rl on . --- on
set trace select off .
set trace rewrite off .
set trace body off .
set trace builtin off .

rew initConfig .
rew numActorMsgsRecvd(addrNStargetANS, initConfig) .
        