load ../../src/probabilistic-model/dns
load ../../src/probabilistic-model/sampler
load ../../src/probabilistic-model/properties

--- This is the initial configuration corresponding to the scenario from attack validation on real
--- implementations for the "Subqueries Unchained" attack.

mod TEST is
  inc SAMPLER + APMAUDE + DNS + PROPERTIES .

  eq rsvTimeout? = false .
  eq rsvTimeout = 1000.0 .

  --- eq maxFetch? = true .
  eq maxFetchParam = 6 .
  eq configWorkBudget = 1000 .

  op testTTL : -> Float .
  eq testTTL = 3600.0 .

  op q : -> Query .
  eq q = query(1, 'del . 'intermediary . 'com . root, a) .

  ops mAddr cAddr rAddr : -> Address .

  --- "SBELT": fallback if there are no known name servers
  op sb : -> ZoneState .
  eq sb = < root ('a . 'root-servers . 'net . root |-> addrRoot) > .

  op cache : -> Cache .
  eq cache =
    cacheEntry(< 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >, 1)
    cacheEntry(< 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS >, 1)
    cacheEntry(< 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >, 1)
    cacheEntry(< 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary >, 1) .

  ops addrRoot addrNScom addrNStargetANS addrNSintermediary : -> Address .

  ops zoneRoot zoneCom zoneTargetANS zoneIntermediary : -> List{Record} .
  eq zoneRoot =
    --- authoritative data
    < root, soa, testTTL, soaData(testTTL) > --- dummy value
    < root, ns, testTTL, 'a . 'root-servers . 'net . root >

    --- non-authoritative data
    < 'a . 'root-servers . 'net . root, a, testTTL, addrRoot >
    < 'com . root, ns, testTTL, 'ns . 'com . root >
    < 'ns . 'com . root, a, testTTL, addrNScom > . --- glue

  eq zoneCom =
    --- authoritative data
    < 'com . root, soa, testTTL, soaData(testTTL) >
    < 'com . root, ns, testTTL, 'ns . 'com . 'root >
    < 'ns . 'com . root, a, testTTL, addrNScom >

    --- non-authoritative data
    < 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >
    < 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS > --- glue
    < 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >
    < 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary > . --- glue

  eq zoneTargetANS =
    --- authoritative data
    < 'target-ans . 'com . root, soa, testTTL, soaData(testTTL) >
    < 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >
    < 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS >

    < 'a1 . 'target-ans . 'com . root, cname, testTTL, 'b1 . 'intermediary . 'com . root >
    < 'c1 . 'target-ans . 'com . root, cname, testTTL, 'd1 . 'intermediary . 'com . root >
    < 'e1 . 'target-ans . 'com . root, cname, testTTL, 'f1 . 'intermediary . 'com . root >
    < 'g1 . 'target-ans . 'com . root, cname, testTTL, 'h1 . 'intermediary . 'com . root >
    < 'i1 . 'target-ans . 'com . root, cname, testTTL, 'j1 . 'intermediary . 'com . root >
    < 'k1 . 'target-ans . 'com . root, cname, testTTL, 'l1 . 'intermediary . 'com . root >
    < 'm1 . 'target-ans . 'com . root, cname, testTTL, 'n1 . 'intermediary . 'com . root >
    < 'o1 . 'target-ans . 'com . root, cname, testTTL, 'p1 . 'intermediary . 'com . root >
    .

  eq zoneIntermediary =
    --- authoritative data
    < 'intermediary . 'com . root, soa, testTTL, soaData(testTTL) >
    < 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >
    < 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary >

    --- malicious delegation
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a1 . 'target-ans . 'com . root >

    --- CNAME chains
    < 'b1 . 'intermediary . 'com . root, cname, testTTL, 'c1 . 'target-ans . 'com . root >
    < 'd1 . 'intermediary . 'com . root, cname, testTTL, 'e1 . 'target-ans . 'com . root >
    < 'f1 . 'intermediary . 'com . root, cname, testTTL, 'g1 . 'target-ans . 'com . root >
    < 'h1 . 'intermediary . 'com . root, cname, testTTL, 'i1 . 'target-ans . 'com . root >
    < 'j1 . 'intermediary . 'com . root, cname, testTTL, 'k1 . 'target-ans . 'com . root >
    < 'l1 . 'intermediary . 'com . root, cname, testTTL, 'm1 . 'target-ans . 'com . root >
    < 'n1 . 'intermediary . 'com . root, cname, testTTL, 'o1 . 'target-ans . 'com . root >
    < 'p1 . 'intermediary . 'com . root, cname, testTTL, 'q1 . 'target-ans . 'com . root >
    .

  op initConfig : -> Config .
  eq initConfig = run(initState, limit) .

  eq initState = { 0.0 | nil }
    --- Preliminaries
    initMonitor(mAddr)
    [id, to cAddr : start, 0]

    < cAddr : Client | queries: q, resolver: rAddr, notifyDone: nullAddr >
    < rAddr : Resolver | cache: cache, --- assuming the name servers of target-ans.com and intermediary.com are cached
                         nxdomainCache: nilNxdomainCache,
                         nodataCache: nilNodataCache,
                         sbelt: sb,
                         workBudget: emptyIN,
                         blockedQueries: eptQSS,
                         sentQueries: eptQSS >

    --- Root name server
    < addrRoot : Nameserver | db: zoneRoot, queue: nilQueue >
    --- .com authoritative name server
    < addrNScom : Nameserver | db: zoneCom, queue: nilQueue >
    --- target-ans.com authoritative name server
    < addrNStargetANS : Nameserver | db: zoneTargetANS, queue: nilQueue >
    --- intermediary.com authoritative name server
    < addrNSintermediary : Nameserver | db: zoneIntermediary, queue: nilQueue > .

endm

--- uncomment for debugging purposes
--- set trace on .

set trace condition off . --- This does not seem to work
set trace whole off .
set trace substitution off .
set trace mb off .
set trace eq off .
set trace rl on . --- on
set trace select off .
set trace rewrite off .
set trace body off .
set trace builtin off .

rew initConfig .

rew numActorMsgsRecvd(addrNStargetANS, initConfig) .
rew msgAmpFactor(cAddr, addrNStargetANS ; addrNSintermediary ; addrNScom, initConfig) .
rew msgAmpFactor(cAddr, addrNStargetANS, initConfig) .
rew msgAmpFactor(cAddr, addrNSintermediary, initConfig) .
rew msgAmpFactor(cAddr, addrNScom, initConfig) .
