load ../../src/probabilistic-model/dns
load ../../src/probabilistic-model/sampler
load ../../src/probabilistic-model/properties

--- This is the initial configuration corresponding to the scenario from attack validation on real
--- implementations for the "Subqueries Unchained" attack.

mod TEST is
  inc SAMPLER + APMAUDE + DNS + PROPERTIES .

  eq rsvTimeout? = false .
  eq rsvTimeout = 1000.0 .

  --- eq maxFetch? = true .
  eq maxFetchParam = 6 .
  eq configWorkBudget = 1000 .

  op testTTL : -> Float .
  eq testTTL = 3600.0 .

  op q : -> Query .
  eq q = query(1, 'del . 'intermediary . 'com . root, a) .

  ops mAddr cAddr rAddr : -> Address .

  --- "SBELT": fallback if there are no known name servers
  op sb : -> ZoneState .
  eq sb = < root ('a . 'root-servers . 'net . root |-> addrRoot) > .

  op cache : -> Cache .
  eq cache =
    cacheEntry(< 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >, 1)
    cacheEntry(< 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS >, 1)
    cacheEntry(< 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >, 1)
    cacheEntry(< 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary >, 1) .

  ops addrRoot addrNScom addrNStargetANS addrNSintermediary : -> Address .

  ops zoneRoot zoneCom zoneTargetANS zoneIntermediary : -> List{Record} .
  eq zoneRoot =
    --- authoritative data
    < root, soa, testTTL, soaData(testTTL) > --- dummy value
    < root, ns, testTTL, 'a . 'root-servers . 'net . root >

    --- non-authoritative data
    < 'a . 'root-servers . 'net . root, a, testTTL, addrRoot >
    < 'com . root, ns, testTTL, 'ns . 'com . root >
    < 'ns . 'com . root, a, testTTL, addrNScom > . --- glue

  eq zoneCom =
    --- authoritative data
    < 'com . root, soa, testTTL, soaData(testTTL) >
    < 'com . root, ns, testTTL, 'ns . 'com . 'root >
    < 'ns . 'com . root, a, testTTL, addrNScom >

    --- non-authoritative data
    < 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >
    < 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS > --- glue
    < 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >
    < 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary > . --- glue

  eq zoneTargetANS =
    --- authoritative data
    < 'target-ans . 'com . root, soa, testTTL, soaData(testTTL) >
    < 'target-ans . 'com . root, ns, testTTL, 'ns . 'target-ans . 'com . root >
    < 'ns . 'target-ans . 'com . root, a, testTTL, addrNStargetANS >

    < 'a1 . 'target-ans . 'com . root, cname, testTTL, 'b1 . 'intermediary . 'com . root >
    < 'c1 . 'target-ans . 'com . root, cname, testTTL, 'd1 . 'intermediary . 'com . root >
    < 'e1 . 'target-ans . 'com . root, cname, testTTL, 'f1 . 'intermediary . 'com . root >
    < 'g1 . 'target-ans . 'com . root, cname, testTTL, 'h1 . 'intermediary . 'com . root >
    < 'i1 . 'target-ans . 'com . root, cname, testTTL, 'j1 . 'intermediary . 'com . root >
    < 'k1 . 'target-ans . 'com . root, cname, testTTL, 'l1 . 'intermediary . 'com . root >
    < 'm1 . 'target-ans . 'com . root, cname, testTTL, 'n1 . 'intermediary . 'com . root >
    < 'o1 . 'target-ans . 'com . root, cname, testTTL, 'p1 . 'intermediary . 'com . root >

    < 'a2 . 'target-ans . 'com . root, cname, testTTL, 'b2 . 'intermediary . 'com . root >
    < 'c2 . 'target-ans . 'com . root, cname, testTTL, 'd2 . 'intermediary . 'com . root >
    < 'e2 . 'target-ans . 'com . root, cname, testTTL, 'f2 . 'intermediary . 'com . root >
    < 'g2 . 'target-ans . 'com . root, cname, testTTL, 'h2 . 'intermediary . 'com . root >
    < 'i2 . 'target-ans . 'com . root, cname, testTTL, 'j2 . 'intermediary . 'com . root >
    < 'k2 . 'target-ans . 'com . root, cname, testTTL, 'l2 . 'intermediary . 'com . root >
    < 'm2 . 'target-ans . 'com . root, cname, testTTL, 'n2 . 'intermediary . 'com . root >
    < 'o2 . 'target-ans . 'com . root, cname, testTTL, 'p2 . 'intermediary . 'com . root >

    < 'a3 . 'target-ans . 'com . root, cname, testTTL, 'b3 . 'intermediary . 'com . root >
    < 'c3 . 'target-ans . 'com . root, cname, testTTL, 'd3 . 'intermediary . 'com . root >
    < 'e3 . 'target-ans . 'com . root, cname, testTTL, 'f3 . 'intermediary . 'com . root >
    < 'g3 . 'target-ans . 'com . root, cname, testTTL, 'h3 . 'intermediary . 'com . root >
    < 'i3 . 'target-ans . 'com . root, cname, testTTL, 'j3 . 'intermediary . 'com . root >
    < 'k3 . 'target-ans . 'com . root, cname, testTTL, 'l3 . 'intermediary . 'com . root >
    < 'm3 . 'target-ans . 'com . root, cname, testTTL, 'n3 . 'intermediary . 'com . root >
    < 'o3 . 'target-ans . 'com . root, cname, testTTL, 'p3 . 'intermediary . 'com . root >

    < 'a4 . 'target-ans . 'com . root, cname, testTTL, 'b4 . 'intermediary . 'com . root >
    < 'c4 . 'target-ans . 'com . root, cname, testTTL, 'd4 . 'intermediary . 'com . root >
    < 'e4 . 'target-ans . 'com . root, cname, testTTL, 'f4 . 'intermediary . 'com . root >
    < 'g4 . 'target-ans . 'com . root, cname, testTTL, 'h4 . 'intermediary . 'com . root >
    < 'i4 . 'target-ans . 'com . root, cname, testTTL, 'j4 . 'intermediary . 'com . root >
    < 'k4 . 'target-ans . 'com . root, cname, testTTL, 'l4 . 'intermediary . 'com . root >
    < 'm4 . 'target-ans . 'com . root, cname, testTTL, 'n4 . 'intermediary . 'com . root >
    < 'o4 . 'target-ans . 'com . root, cname, testTTL, 'p4 . 'intermediary . 'com . root >

    < 'a5 . 'target-ans . 'com . root, cname, testTTL, 'b5 . 'intermediary . 'com . root >
    < 'c5 . 'target-ans . 'com . root, cname, testTTL, 'd5 . 'intermediary . 'com . root >
    < 'e5 . 'target-ans . 'com . root, cname, testTTL, 'f5 . 'intermediary . 'com . root >
    < 'g5 . 'target-ans . 'com . root, cname, testTTL, 'h5 . 'intermediary . 'com . root >
    < 'i5 . 'target-ans . 'com . root, cname, testTTL, 'j5 . 'intermediary . 'com . root >
    < 'k5 . 'target-ans . 'com . root, cname, testTTL, 'l5 . 'intermediary . 'com . root >
    < 'm5 . 'target-ans . 'com . root, cname, testTTL, 'n5 . 'intermediary . 'com . root >
    < 'o5 . 'target-ans . 'com . root, cname, testTTL, 'p5 . 'intermediary . 'com . root >

    < 'a6 . 'target-ans . 'com . root, cname, testTTL, 'b6 . 'intermediary . 'com . root >
    < 'c6 . 'target-ans . 'com . root, cname, testTTL, 'd6 . 'intermediary . 'com . root >
    < 'e6 . 'target-ans . 'com . root, cname, testTTL, 'f6 . 'intermediary . 'com . root >
    < 'g6 . 'target-ans . 'com . root, cname, testTTL, 'h6 . 'intermediary . 'com . root >
    < 'i6 . 'target-ans . 'com . root, cname, testTTL, 'j6 . 'intermediary . 'com . root >
    < 'k6 . 'target-ans . 'com . root, cname, testTTL, 'l6 . 'intermediary . 'com . root >
    < 'm6 . 'target-ans . 'com . root, cname, testTTL, 'n6 . 'intermediary . 'com . root >
    < 'o6 . 'target-ans . 'com . root, cname, testTTL, 'p6 . 'intermediary . 'com . root >

    < 'a7 . 'target-ans . 'com . root, cname, testTTL, 'b7 . 'intermediary . 'com . root >
    < 'c7 . 'target-ans . 'com . root, cname, testTTL, 'd7 . 'intermediary . 'com . root >
    < 'e7 . 'target-ans . 'com . root, cname, testTTL, 'f7 . 'intermediary . 'com . root >
    < 'g7 . 'target-ans . 'com . root, cname, testTTL, 'h7 . 'intermediary . 'com . root >
    < 'i7 . 'target-ans . 'com . root, cname, testTTL, 'j7 . 'intermediary . 'com . root >
    < 'k7 . 'target-ans . 'com . root, cname, testTTL, 'l7 . 'intermediary . 'com . root >
    < 'm7 . 'target-ans . 'com . root, cname, testTTL, 'n7 . 'intermediary . 'com . root >
    < 'o7 . 'target-ans . 'com . root, cname, testTTL, 'p7 . 'intermediary . 'com . root >

    < 'a8 . 'target-ans . 'com . root, cname, testTTL, 'b8 . 'intermediary . 'com . root >
    < 'c8 . 'target-ans . 'com . root, cname, testTTL, 'd8 . 'intermediary . 'com . root >
    < 'e8 . 'target-ans . 'com . root, cname, testTTL, 'f8 . 'intermediary . 'com . root >
    < 'g8 . 'target-ans . 'com . root, cname, testTTL, 'h8 . 'intermediary . 'com . root >
    < 'i8 . 'target-ans . 'com . root, cname, testTTL, 'j8 . 'intermediary . 'com . root >
    < 'k8 . 'target-ans . 'com . root, cname, testTTL, 'l8 . 'intermediary . 'com . root >
    < 'm8 . 'target-ans . 'com . root, cname, testTTL, 'n8 . 'intermediary . 'com . root >
    < 'o8 . 'target-ans . 'com . root, cname, testTTL, 'p8 . 'intermediary . 'com . root >

    < 'a9 . 'target-ans . 'com . root, cname, testTTL, 'b9 . 'intermediary . 'com . root >
    < 'c9 . 'target-ans . 'com . root, cname, testTTL, 'd9 . 'intermediary . 'com . root >
    < 'e9 . 'target-ans . 'com . root, cname, testTTL, 'f9 . 'intermediary . 'com . root >
    < 'g9 . 'target-ans . 'com . root, cname, testTTL, 'h9 . 'intermediary . 'com . root >
    < 'i9 . 'target-ans . 'com . root, cname, testTTL, 'j9 . 'intermediary . 'com . root >
    < 'k9 . 'target-ans . 'com . root, cname, testTTL, 'l9 . 'intermediary . 'com . root >
    < 'm9 . 'target-ans . 'com . root, cname, testTTL, 'n9 . 'intermediary . 'com . root >
    < 'o9 . 'target-ans . 'com . root, cname, testTTL, 'p9 . 'intermediary . 'com . root >

    < 'a10 . 'target-ans . 'com . root, cname, testTTL, 'b10 . 'intermediary . 'com . root >
    < 'c10 . 'target-ans . 'com . root, cname, testTTL, 'd10 . 'intermediary . 'com . root >
    < 'e10 . 'target-ans . 'com . root, cname, testTTL, 'f10 . 'intermediary . 'com . root >
    < 'g10 . 'target-ans . 'com . root, cname, testTTL, 'h10 . 'intermediary . 'com . root >
    < 'i10 . 'target-ans . 'com . root, cname, testTTL, 'j10 . 'intermediary . 'com . root >
    < 'k10 . 'target-ans . 'com . root, cname, testTTL, 'l10 . 'intermediary . 'com . root >
    < 'm10 . 'target-ans . 'com . root, cname, testTTL, 'n10 . 'intermediary . 'com . root >
    < 'o10 . 'target-ans . 'com . root, cname, testTTL, 'p10 . 'intermediary . 'com . root >
    .

  eq zoneIntermediary =
    --- authoritative data
    < 'intermediary . 'com . root, soa, testTTL, soaData(testTTL) >
    < 'intermediary . 'com . root, ns, testTTL, 'ns . 'intermediary . 'com . root >
    < 'ns . 'intermediary . 'com . root, a, testTTL, addrNSintermediary >

    --- malicious delegation
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a1 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a2 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a3 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a4 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a5 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a6 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a7 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a8 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a9 . 'target-ans . 'com . root >
    < 'del . 'intermediary . 'com . root, ns, testTTL, 'a10 . 'target-ans . 'com . root >

    --- CNAME chains
    < 'b1 . 'intermediary . 'com . root, cname, testTTL, 'c1 . 'target-ans . 'com . root >
    < 'd1 . 'intermediary . 'com . root, cname, testTTL, 'e1 . 'target-ans . 'com . root >
    < 'f1 . 'intermediary . 'com . root, cname, testTTL, 'g1 . 'target-ans . 'com . root >
    < 'h1 . 'intermediary . 'com . root, cname, testTTL, 'i1 . 'target-ans . 'com . root >
    < 'j1 . 'intermediary . 'com . root, cname, testTTL, 'k1 . 'target-ans . 'com . root >
    < 'l1 . 'intermediary . 'com . root, cname, testTTL, 'm1 . 'target-ans . 'com . root >
    < 'n1 . 'intermediary . 'com . root, cname, testTTL, 'o1 . 'target-ans . 'com . root >
    < 'p1 . 'intermediary . 'com . root, cname, testTTL, 'q1 . 'target-ans . 'com . root >

    < 'b2 . 'intermediary . 'com . root, cname, testTTL, 'c2 . 'target-ans . 'com . root >
    < 'd2 . 'intermediary . 'com . root, cname, testTTL, 'e2 . 'target-ans . 'com . root >
    < 'f2 . 'intermediary . 'com . root, cname, testTTL, 'g2 . 'target-ans . 'com . root >
    < 'h2 . 'intermediary . 'com . root, cname, testTTL, 'i2 . 'target-ans . 'com . root >
    < 'j2 . 'intermediary . 'com . root, cname, testTTL, 'k2 . 'target-ans . 'com . root >
    < 'l2 . 'intermediary . 'com . root, cname, testTTL, 'm2 . 'target-ans . 'com . root >
    < 'n2 . 'intermediary . 'com . root, cname, testTTL, 'o2 . 'target-ans . 'com . root >
    < 'p2 . 'intermediary . 'com . root, cname, testTTL, 'q2 . 'target-ans . 'com . root >

    < 'b3 . 'intermediary . 'com . root, cname, testTTL, 'c3 . 'target-ans . 'com . root >
    < 'd3 . 'intermediary . 'com . root, cname, testTTL, 'e3 . 'target-ans . 'com . root >
    < 'f3 . 'intermediary . 'com . root, cname, testTTL, 'g3 . 'target-ans . 'com . root >
    < 'h3 . 'intermediary . 'com . root, cname, testTTL, 'i3 . 'target-ans . 'com . root >
    < 'j3 . 'intermediary . 'com . root, cname, testTTL, 'k3 . 'target-ans . 'com . root >
    < 'l3 . 'intermediary . 'com . root, cname, testTTL, 'm3 . 'target-ans . 'com . root >
    < 'n3 . 'intermediary . 'com . root, cname, testTTL, 'o3 . 'target-ans . 'com . root >
    < 'p3 . 'intermediary . 'com . root, cname, testTTL, 'q3 . 'target-ans . 'com . root >

    < 'b4 . 'intermediary . 'com . root, cname, testTTL, 'c4 . 'target-ans . 'com . root >
    < 'd4 . 'intermediary . 'com . root, cname, testTTL, 'e4 . 'target-ans . 'com . root >
    < 'f4 . 'intermediary . 'com . root, cname, testTTL, 'g4 . 'target-ans . 'com . root >
    < 'h4 . 'intermediary . 'com . root, cname, testTTL, 'i4 . 'target-ans . 'com . root >
    < 'j4 . 'intermediary . 'com . root, cname, testTTL, 'k4 . 'target-ans . 'com . root >
    < 'l4 . 'intermediary . 'com . root, cname, testTTL, 'm4 . 'target-ans . 'com . root >
    < 'n4 . 'intermediary . 'com . root, cname, testTTL, 'o4 . 'target-ans . 'com . root >
    < 'p4 . 'intermediary . 'com . root, cname, testTTL, 'q4 . 'target-ans . 'com . root >

    < 'b5 . 'intermediary . 'com . root, cname, testTTL, 'c5 . 'target-ans . 'com . root >
    < 'd5 . 'intermediary . 'com . root, cname, testTTL, 'e5 . 'target-ans . 'com . root >
    < 'f5 . 'intermediary . 'com . root, cname, testTTL, 'g5 . 'target-ans . 'com . root >
    < 'h5 . 'intermediary . 'com . root, cname, testTTL, 'i5 . 'target-ans . 'com . root >
    < 'j5 . 'intermediary . 'com . root, cname, testTTL, 'k5 . 'target-ans . 'com . root >
    < 'l5 . 'intermediary . 'com . root, cname, testTTL, 'm5 . 'target-ans . 'com . root >
    < 'n5 . 'intermediary . 'com . root, cname, testTTL, 'o5 . 'target-ans . 'com . root >
    < 'p5 . 'intermediary . 'com . root, cname, testTTL, 'q5 . 'target-ans . 'com . root >

    < 'b6 . 'intermediary . 'com . root, cname, testTTL, 'c6 . 'target-ans . 'com . root >
    < 'd6 . 'intermediary . 'com . root, cname, testTTL, 'e6 . 'target-ans . 'com . root >
    < 'f6 . 'intermediary . 'com . root, cname, testTTL, 'g6 . 'target-ans . 'com . root >
    < 'h6 . 'intermediary . 'com . root, cname, testTTL, 'i6 . 'target-ans . 'com . root >
    < 'j6 . 'intermediary . 'com . root, cname, testTTL, 'k6 . 'target-ans . 'com . root >
    < 'l6 . 'intermediary . 'com . root, cname, testTTL, 'm6 . 'target-ans . 'com . root >
    < 'n6 . 'intermediary . 'com . root, cname, testTTL, 'o6 . 'target-ans . 'com . root >
    < 'p6 . 'intermediary . 'com . root, cname, testTTL, 'q6 . 'target-ans . 'com . root >

    < 'b7 . 'intermediary . 'com . root, cname, testTTL, 'c7 . 'target-ans . 'com . root >
    < 'd7 . 'intermediary . 'com . root, cname, testTTL, 'e7 . 'target-ans . 'com . root >
    < 'f7 . 'intermediary . 'com . root, cname, testTTL, 'g7 . 'target-ans . 'com . root >
    < 'h7 . 'intermediary . 'com . root, cname, testTTL, 'i7 . 'target-ans . 'com . root >
    < 'j7 . 'intermediary . 'com . root, cname, testTTL, 'k7 . 'target-ans . 'com . root >
    < 'l7 . 'intermediary . 'com . root, cname, testTTL, 'm7 . 'target-ans . 'com . root >
    < 'n7 . 'intermediary . 'com . root, cname, testTTL, 'o7 . 'target-ans . 'com . root >
    < 'p7 . 'intermediary . 'com . root, cname, testTTL, 'q7 . 'target-ans . 'com . root >

    < 'b8 . 'intermediary . 'com . root, cname, testTTL, 'c8 . 'target-ans . 'com . root >
    < 'd8 . 'intermediary . 'com . root, cname, testTTL, 'e8 . 'target-ans . 'com . root >
    < 'f8 . 'intermediary . 'com . root, cname, testTTL, 'g8 . 'target-ans . 'com . root >
    < 'h8 . 'intermediary . 'com . root, cname, testTTL, 'i8 . 'target-ans . 'com . root >
    < 'j8 . 'intermediary . 'com . root, cname, testTTL, 'k8 . 'target-ans . 'com . root >
    < 'l8 . 'intermediary . 'com . root, cname, testTTL, 'm8 . 'target-ans . 'com . root >
    < 'n8 . 'intermediary . 'com . root, cname, testTTL, 'o8 . 'target-ans . 'com . root >
    < 'p8 . 'intermediary . 'com . root, cname, testTTL, 'q8 . 'target-ans . 'com . root >

    < 'b9 . 'intermediary . 'com . root, cname, testTTL, 'c9 . 'target-ans . 'com . root >
    < 'd9 . 'intermediary . 'com . root, cname, testTTL, 'e9 . 'target-ans . 'com . root >
    < 'f9 . 'intermediary . 'com . root, cname, testTTL, 'g9 . 'target-ans . 'com . root >
    < 'h9 . 'intermediary . 'com . root, cname, testTTL, 'i9 . 'target-ans . 'com . root >
    < 'j9 . 'intermediary . 'com . root, cname, testTTL, 'k9 . 'target-ans . 'com . root >
    < 'l9 . 'intermediary . 'com . root, cname, testTTL, 'm9 . 'target-ans . 'com . root >
    < 'n9 . 'intermediary . 'com . root, cname, testTTL, 'o9 . 'target-ans . 'com . root >
    < 'p9 . 'intermediary . 'com . root, cname, testTTL, 'q9 . 'target-ans . 'com . root >

    < 'b10 . 'intermediary . 'com . root, cname, testTTL, 'c10 . 'target-ans . 'com . root >
    < 'd10 . 'intermediary . 'com . root, cname, testTTL, 'e10 . 'target-ans . 'com . root >
    < 'f10 . 'intermediary . 'com . root, cname, testTTL, 'g10 . 'target-ans . 'com . root >
    < 'h10 . 'intermediary . 'com . root, cname, testTTL, 'i10 . 'target-ans . 'com . root >
    < 'j10 . 'intermediary . 'com . root, cname, testTTL, 'k10 . 'target-ans . 'com . root >
    < 'l10 . 'intermediary . 'com . root, cname, testTTL, 'm10 . 'target-ans . 'com . root >
    < 'n10 . 'intermediary . 'com . root, cname, testTTL, 'o10 . 'target-ans . 'com . root >
    < 'p10 . 'intermediary . 'com . root, cname, testTTL, 'q10 . 'target-ans . 'com . root >
    .

  op initConfig : -> Config .
  eq initConfig = run(initState, limit) .

  eq initState = { 0.0 | nil }
    --- Preliminaries
    initMonitor(mAddr)
    [id, to cAddr : start, 0]

    < cAddr : Client | queries: q, resolver: rAddr, notifyDone: nullAddr >
    < rAddr : Resolver | cache: cache, --- assuming the name servers of target-ans.com and intermediary.com are cached
                         nxdomainCache: nilNxdomainCache,
                         nodataCache: nilNodataCache,
                         sbelt: sb,
                         workBudget: emptyIN,
                         blockedQueries: eptQSS,
                         sentQueries: eptQSS >

    --- Root name server
    < addrRoot : Nameserver | db: zoneRoot, queue: nilQueue >
    --- .com authoritative name server
    < addrNScom : Nameserver | db: zoneCom, queue: nilQueue >
    --- target-ans.com authoritative name server
    < addrNStargetANS : Nameserver | db: zoneTargetANS, queue: nilQueue >
    --- intermediary.com authoritative name server
    < addrNSintermediary : Nameserver | db: zoneIntermediary, queue: nilQueue > .

endm

--- uncomment for debugging purposes
--- set trace on .

set trace condition off . --- This does not seem to work
set trace whole off .
set trace substitution off .
set trace mb off .
set trace eq off .
set trace rl on . --- on
set trace select off .
set trace rewrite off .
set trace body off .
set trace builtin off .

rew initConfig .

rew msgAmpFactor(cAddr, addrNStargetANS ; addrNSintermediary ; addrNScom, initConfig) .
rew msgAmpFactor(cAddr, addrNStargetANS, initConfig) .
rew msgAmpFactor(cAddr, addrNSintermediary, initConfig) .
rew msgAmpFactor(cAddr, addrNScom, initConfig) .
