load ../../src/probabilistic-model/dns
load ../../src/probabilistic-model/sampler
load ../../src/probabilistic-model/properties

--- This is variant (b) of the NXNS attack, i.e., the victim are the name servers of a SLD.

mod TEST is
  inc SAMPLER + APMAUDE + DNS + PROPERTIES .

  --- uncomment to enable MaxFetch(1) mitigation
  --- eq maxFetch? = true .
  eq maxFetchParam = 1 .

  op testTTL : -> Float .
  eq testTTL = 3600.0 . --- Note that this is in time units, not seconds

  op q : -> Query .
  eq q = query(1, 'nxdomain . 'sd0 . 'attacker . 'com . root, a) .

  ops mAddr cAddr rAddr : -> Address .

  --- "SBELT": fallback if there are no known name servers
  op sb : -> ZoneState .
  eq sb = < root ('a . 'root-servers . 'net . root |-> addrRoot) > .

  op cache : -> Cache .
  eq cache =
    cacheEntry(< 'victim . 'com . root, ns, testTTL, 'ns . 'victim . 'com . root >, 1)
    cacheEntry(< 'ns . 'victim . 'com . root, a, testTTL, addrNSvictim >, 1) .

  ops addrRoot addrNScom addrNSvictim addrNSattacker : -> Address .

  ops zoneRoot zoneCom zoneVictim zoneAttacker : -> List{Record} .
  eq zoneRoot =
    --- authoritative data
    < root, soa, testTTL, soaData(testTTL) > --- dummy value
    < root, ns, testTTL, 'a . 'root-servers . 'net . root >

    --- non-authoritative data
    < 'a . 'root-servers . 'net . root, a, testTTL, addrRoot >
    < 'com . root, ns, testTTL, 'ns . 'com . root >
    < 'ns . 'com . root, a, testTTL, addrNScom > . --- glue

  eq zoneCom =
    --- authoritative data
    < 'com . root, soa, testTTL, soaData(testTTL) >
    < 'com . root, ns, testTTL, 'ns . 'com . 'root >
    < 'ns . 'com . root, a, testTTL, addrNScom >

    --- non-authoritative data
    < 'attacker . 'com . root, ns, testTTL, 'ns . 'attacker . 'com . root >
    < 'ns . 'attacker . 'com . root, a, testTTL, addrNSattacker > --- glue

    < 'victim . 'com . root, ns, testTTL, 'ns . 'victim . 'com . root >
    < 'ns . 'victim . 'com . root, a, testTTL, addrNSvictim > . --- glue

  eq zoneVictim =
    --- authoritative data
    < 'victim . 'com . root, soa, testTTL, soaData(testTTL) >
    < 'victim . 'com . root, ns, testTTL, 'ns . 'victim . 'com . root >
    < 'ns . 'victim . 'com . root, a, testTTL, addrNSvictim > .

  eq zoneAttacker =
    --- authoritative data
    < 'attacker . 'com . root, soa, testTTL, soaData(testTTL) >
    < 'attacker . 'com . root, ns, testTTL, 'ns . 'attacker . 'com . root >
    < 'ns . 'attacker . 'com . root, a, testTTL, addrNSattacker >

    --- Fake delegations for sd0, illustrated using 20 NS records
    --- In practice (BIND), the max number is limited by by the max-recursion-queries parameter.
    --- The paper determined 37 to be the best number if the resolver uses IPv6 and IPv4 (74 if only IPv4 is used).
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens1 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens2 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens3 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens4 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens5 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens6 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens7 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens8 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens9 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens10 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens11 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens12 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens13 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens14 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens15 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens16 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens17 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens18 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens19 . 'victim . 'com . root >
    < 'sd0 . 'attacker . 'com . root, ns, testTTL, 'fakens20 . 'victim . 'com . root > .

  op initConfig : -> Config .
  eq initConfig = run(initState, limit) .

  eq initState = { 0.0 | nil }
    --- Preliminaries
    initMonitor(mAddr)
    [id, to cAddr : start, 0]

    < cAddr : Client | queries: q, resolver: rAddr, notifyDone: nullAddr >
    < rAddr : Resolver | cache: cache, --- assuming the victim.com name servers are cached
                         nxdomainCache: nilNxdomainCache,
                         nodataCache: nilNodataCache,
                         sbelt: sb,
                         workBudget: emptyIN,
                         blockedQueries: eptQSS,
                         sentQueries: eptQSS >

    --- Root name server
    < addrRoot : Nameserver | db: zoneRoot, queue: nilQueue >
    --- .com authoritative name server
    < addrNScom : Nameserver | db: zoneCom, queue: nilQueue >
    --- victim.com authoritative name server
    < addrNSvictim : Nameserver | db: zoneVictim, queue: nilQueue >
    --- attacker's authoritative name server
    < addrNSattacker : Nameserver | db: zoneAttacker, queue: nilQueue > .

endm

--- uncomment for debugging purposes
--- set trace on .

set trace condition off . --- This does not seem to work
set trace whole off .
set trace substitution off .
set trace mb off .
set trace eq off .
set trace rl on . --- on
set trace select off .
set trace rewrite off .
set trace body off .
set trace builtin off .

rew initConfig .
--- rew numActorMsgsRecvd(addrNSvictim, initConfig) .
--- rew numActorMsgsSent(cAddr ; addrNSattacker, initConfig) .
rew msgAmpFactor(cAddr ; addrNSattacker, addrNSvictim, initConfig) .
